"""rename assessment column to status

Revision ID: 8d488d333771
Revises: e359c6fa2e39
Create Date: 2026-07-19 00:33:43.209046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d488d333771'
down_revision: Union[str, Sequence[str], None] = 'e359c6fa2e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_assessments', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('monthly_assessments', 'assessment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_assessments', sa.Column('assessment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('monthly_assessments', 'status')
    # ### end Alembic commands ###
